# ----------------------------------------------------- 
#  Appearance & Styling (Catppuccin Mocha)
# ----------------------------------------------------- 
general {
    gaps_in = 5
    gaps_out = 10
    border_size = 2
    
    # Catppuccin Mocha Mauve to Blue gradient for active border
    col.active_border = rgb(cba6f7) rgb(89b4fa) 45deg
    
    # Surface0 for inactive border
    col.inactive_border = rgb(313244)
    
    resize_on_border = true
}

decoration {
    rounding = 12

    # Opacity
    active_opacity = 1.0
    inactive_opacity = 0.92

    # Blur
    blur {
        enabled = true
        size = 5
        passes = 3
        new_optimizations = true
        ignore_opacity = on
        xray = false
    }

    # Shadow (Catppuccin Mocha Base for shadow)
    drop_shadow = true
    shadow_range = 15
    shadow_render_power = 3
    col.shadow = rgba(1e1e2e99)
}
