# ----------------------------------------------------- 
#  Monitors Config
# ----------------------------------------------------- 

# Laptop monitor (auto detect and set preferred resolution)
monitor=,preferred,auto,1

# Example for external monitors (uncomment and adjust as needed)
# monitor=DP-1, 1920x1080@144, 1920x0, 1
# monitor=HDMI-A-1, 2560x1440@144, 0x0, 1.25

# Mirroring example
# monitor=DP-1, 1920x1080@60, 0x0, 1, mirror, eDP-1
